export const productsWithoutTopup = [
  'Devil May Cry HD',
  'Resident Evil Village',
  'The Last of Us Part II',
  'Detroit Become Human',
  'DARK SOULS REMASTERED',
  'Resident Evil 4',
  'Metro Redux',
  'DOOM The Dark Ages',
  'Battlefield 2042',
  'Clair Obscur Expedition 33',
  'Resident Evil Remake',
  'Legacy of Kain Soul Reaver',
  'RESIDENT EVIL 2',
  'PUBG Battleground',
  'League Of Legends',
  'Steam',
  'Valorant',
  'Test',
  'Sid Meiers Civilization VI',
  'Black Desert',
  'Mortal Kombat 11',
  'Mafia III',
  'World of Warcraft',
  'God of War Ragnarok',
  'Devil May Cry 4',
  'Fortnite',
  'ARC Raiders',
  'Point Blank',
  'LEGO Star Wars',
  'Razer Gold',
  'Battle.net',
  'Xbox',
  'New State Mobile',
  'Street Fighter 6',
  'Minecraft',
  'Nintendo',
  'Playstation',
  'Arena Breakout',
  'MORTAL KOMBAT XL',
  'Apex Legends Mobile',
];
